###
POST http://localhost:3000/employees
Content-Type: application/json

{
  "fullName": "deggau",
  "email": "deggau7@email.com"
}

###
GET http://localhost:3000/employees

###
GET http://localhost:3000/employees/2

###
PATCH http://localhost:3000/employees/2
Content-Type: application/json

{
  "fullName": "deggauuuuuuu"
}

###
DELETE http://localhost:3000/employees/3

